version: "3"

networks:
      gitea:
        external: false
volumes:
      git_data:
        driver: local
      
      db_data:
        driver: local

services:
      gitea:
        image: gitea/gitea:latest
        container_name: gitea
        environment:
          - DB_TYPE=postgres
          - DB_HOST=db:5432
          - DB_NAME=gitea
          - DB_USER=gitea
          - DB_PASSWD=git21Ta33teea
          - USER_UID=1000
          - USER_GID=1000
        restart: always
        volumes:
          - ./git_data:/data
          - /etc/timezone:/etc/timezone:ro
          - /etc/localtime:/etc/localtime:ro
        ports:
          - 3000:3000
          - 22:22
        depends_on:
          - db
        
      db:
        image: postgres:alpine
        container_name: postgres
        environment:
          - POSTGRES_USER=gitea
          - POSTGRES_PASSWORD=git21Ta33teea
          - POSTGRES_DB=gitea
        restart: always
        volumes:
          - ./db_data:/var/lib/postgresql/data
        expose:
          - 5432
 